### ISSUE TITLE
PHP warning on feof

### ISSUE THREAD

**Issue by Cach54** [thecodingmachine/utils.cache.file-cache#8]
I get alot of errors like 

> PHP Warning:  fread() expects parameter 1 to be resource, boolean given in /data/www/pht/webikeo/prod/vendor/mouf/utils.cache.file-cache/src/FileCache.php on line 73, referer: ...

The code being

```
$fp = fopen($filename, "r");
            $timeout = fgets($fp);

            if ($timeout > time() || $timeout==0) {
                $contents = "";
                while (!feof($fp)) {
                  $contents .= fread($fp, 65536);
                }
...
```

My current version of the package is v2.1.3

**Comment by moufmouf** [comment]
This is solved in v2.2.0
